Xpos334/Xpos334/Models/ErrorViewModel.cs
namespace Xpos334.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Xpos334/Xpos334/Models/Friend.cs
namespace Xpos334.Models
{
    public class Friend
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string address { get; set; }
    }
}

Xpos334/Xpos334/Controllers/FriendController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography.X509Certificates;
using Xpos334.Models;

namespace Xpos334.Controllers
{
    public class FriendController : Controller
    {
         private static List<Friend> friends = new List<Friend>()
           {
               new Friend(){Id = 1, Name = "Irvan", address = "Kemayoran"},
               new Friend(){Id = 2, Name = "Tunggul", address = "Cilandak"},
               new Friend(){Id = 3, Name = "Shabrina", address = "Radio Dalam"}
           };
        public IActionResult Index()
        {
            

            /* List<Friend> friends = new List<Friend>()
             {
                 new Friend(){Id = 1, Name = "Irvan", address = "Kemayoran"},
                 new Friend(){Id = 2, Name = "Tunggul", address = "Cilandak"},
                 new Friend(){Id = 3, Name = "Shabrina", address = "Radio Dalam"}
             };*/

            ViewBag.listFriend = friends;

            return View();
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Friend friend)
        {
            friends.Add(friend);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
          //  Friend friend = friends[id];
            Friend friend = friends.Find(a => a.Id == id)!;  //tanda seru penghilang garis bawah doang (NGGA NGARUH)
            return View(friend);
        }

        [HttpPost]
        public IActionResult Edit(Friend data)
        {
            Friend friend = friends.Find(a => a.Id == data.Id)!;
            int index = friends.IndexOf(friend);
            if (index >-1 ){
                friends[index].Name = data.Name;
                friends[index].address = data.address;

            }
            return RedirectToAction("Index");
        }

        public IActionResult Detail(int id)
        {
            //  Friend friend = friends[id];
            Friend friend = friends.Find(a => a.Id == id)!;  //tanda seru penghilang garis bawah doang (NGGA NGARUH)
            return View(friend);
        }

        public IActionResult Delete(int id)
        {
            //  Friend friend = friends[id];
            Friend friend = friends.Find(a => a.Id == id)!;  //tanda seru penghilang garis bawah doang (NGGA NGARUH)
            return View(friend);
        }

        [HttpPost]
        public IActionResult Delete(Friend data)
        {
            Friend friend =  friends.Find(a =>a.Id == data.Id);
            friends.Remove(friend);
            return RedirectToAction("Index");
        }
    }
}

Xpos334/Xpos334/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Xpos334.Models;

namespace Xpos334.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Xpos334/Xpos334/Views/Friend/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Create Friend";
}
<div class="h4 ab-4">Create Form Friend</div>

<form asp-action="Create" method="post" >
    <div class="form-group row">
        <label for="Id" class="col-sm-2 col-form-label">Id</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="Id" name="Id">
        </div>
    </div>
    <div class="form-group row">
        <label for="Address" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="Name" name="Name">
        </div>
    </div>
    <div class="form-group row">
        <label for="Address" class="col-sm-2 col-form-label">Address</label>
        <div class="col-sm-10">
            <textarea type="text" class="form-control" id="Address" name="Address" ></textarea>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a class="btn btn-light" asp-asp-controller="Friend" asp-action="Index">Bact To List</a>
        </div>
    </div>
</form>

Xpos334/Xpos334/Views/Friend/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Friend //Opsional
@{
    ViewData["Title"] = "Delete Friend";

}

<div>Are you sure delete @Model.Name Data?</div>

<form action="Delete" method="post">
<div class="form-group row">
    <input type="hidden" id="id" name="Id" value="@Model.Id"></input>
    <div>
        <button type="submit" class="btn btn-warning">Submit</button>
        <a class="btn btn-light" asp-asp-controller="Friend" asp-action="Index">Bact To List</a>
    </div>
</div>
</form>

Xpos334/Xpos334/Views/Friend/Detail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Friend //Opsional
@{
    ViewData["Title"] = "Detail Friend";

}

<div class="h4 ab-4">Edit Form Friend</div>

<div >
    <div class="form-group row">
        <label for="Id" class="col-sm-2 col-form-label">Id</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="Id" name="Id" value="@Model.Id" readonly>
        </div>
    </div>
    <div class="form-group row">
        <label for="Address" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name" readonly>
        </div>
    </div>
    <div class="form-group row">
        <label for="Address" class="col-sm-2 col-form-label">Address</label>
        <div class="col-sm-10">
            <textarea type="text" class="form-control" id="Address" name="Address" readonly>@Model.address</textarea>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <a class="btn btn-light" asp-asp-controller="Friend" asp-action="Index">Bact To List</a>
        </div>
    </div>
</div>

Xpos334/Xpos334/Views/Friend/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Friend //Opsional
@{
    ViewData["Title"] = "Edit Friend";

}

<div class="h4 ab-4">Edit Form Friend</div>

<form asp-action="Edit" method="post">
    <div class="form-group row">
        <label for="Id" class="col-sm-2 col-form-label">Id</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="Id" name="Id" value="@Model.Id" readonly>
        </div>
    </div>
    <div class="form-group row">
        <label for="Address" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name">
        </div>
    </div>
    <div class="form-group row">
        <label for="Address" class="col-sm-2 col-form-label">Address</label>
        <div class="col-sm-10">
            <textarea type="text" class="form-control" id="Address" name="Address" >@Model.address</textarea>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a class="btn btn-light" asp-asp-controller="Friend" asp-action="Index">Bact To List</a>
        </div>
    </div>
</form>

Xpos334/Xpos334/Views/Friend/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Page Friend";
}

<h1>@ViewData["Title"]</h1>

<a class="btn btn-primary" asp-controller="Friend" asp-action="Create">Create</a>

<table class="table table-hover">

    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Address</th>
            <th>Action</th> <!-- Untuk Menaruh tombol delete update dll-->
        </tr>
    </thead>
    <tbody>

        @foreach (Friend item in ViewBag.listFriend)
        //@foreach (Friend item in Model)
        {
            <tr>
                <th scope="row">@item.Id</th>
                <td>@item.Name</td>
                <td>@item.address</td>
                <td>
                    <a class="btn btn-primary" asp-controller="Friend" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    <a class="btn btn-success" asp-controller="Friend" asp-action="Detail" asp-route-id="@item.Id">Detail</a>
                    <a class="btn btn-danger" asp-controller="Friend" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Xpos334/Xpos334/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Xpos 334</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Xpos334/Xpos334/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Xpos334</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Xpos334.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Xpos334</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Friend" asp-action="index">Friend</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Xpos334 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>